# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Madeline L. Galbraith 
email: madeline.l.galbraith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a PhD candidate at Rice University in the Center for Theoretical Biological Physics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://madgal.github.io" # the base hostname & protocol for your site
github_username:  madgal
orcid_username: 0000-0003-1735-0747
linkedin_username: madeline-galbraith-physicist
 
# Build settings
markdown: kramdown

#collections:
#   CodeSamples:
#     java:
#      output: true
#      permalink: /CodeSamples/java/
